import * as fs from 'fs';
import * as path from 'path';
import { logger } from '../../core/logger.js';

interface LaunchConfig {
  version: string;
  configurations: DebugConfig[];
}

interface DebugConfig {
  name: string;
  type: string;
  request: string;
  port?: number;
  [key: string]: unknown;
}

const LAUNCH_CONFIG_PREFIX = 'SAP Debug:';

export function readLaunchJson(workspacePath: string): LaunchConfig {
  const launchPath = path.join(workspacePath, '.vscode', 'launch.json');
  try {
    const raw = fs.readFileSync(launchPath, 'utf-8');
    return JSON.parse(raw) as LaunchConfig;
  } catch {
    return { version: '0.2.0', configurations: [] };
  }
}

export function writeLaunchJson(workspacePath: string, config: LaunchConfig): void {
  const vscodeDir = path.join(workspacePath, '.vscode');
  if (!fs.existsSync(vscodeDir)) {
    fs.mkdirSync(vscodeDir, { recursive: true });
  }
  const launchPath = path.join(vscodeDir, 'launch.json');
  fs.writeFileSync(launchPath, `${JSON.stringify(config, null, 2)  }\n`, 'utf-8');
  logger.info(`Wrote launch.json at ${launchPath}`);
}

export interface MergeLaunchOptions {
  appName: string;
  port: number;
  localFolderPath: string;
}

/**
 * Merges a new CDS debug configuration into launch.json.
 * Replaces existing config with same name, preserves others.
 * Returns the config name to use with vscode.debug.startDebugging().
 */
export function mergeLaunchConfig(workspacePath: string, opts: MergeLaunchOptions): string {
  const configName = `${LAUNCH_CONFIG_PREFIX} ${opts.appName}`;
  const existing = readLaunchJson(workspacePath);

  const newConfig: DebugConfig = {
    name: configName,
    type: 'node',
    request: 'attach',
    port: opts.port,
    restart: true,
    sourceMaps: true,
    skipFiles: ['<node_internals>/**'],
    remoteRoot: '/home/vcap/app',
    localRoot: opts.localFolderPath,
  };

  const filtered = existing.configurations.filter(c => c.name !== configName);
  existing.configurations = [...filtered, newConfig];

  writeLaunchJson(workspacePath, existing);
  return configName;
}

/**
 * Removes all SAP Debug configs generated by this extension from launch.json.
 */
export function cleanupLaunchConfigs(workspacePath: string): void {
  const existing = readLaunchJson(workspacePath);
  existing.configurations = existing.configurations.filter(
    c => !c.name.startsWith(LAUNCH_CONFIG_PREFIX),
  );
  writeLaunchJson(workspacePath, existing);
}

/**
 * Collects all ports currently used by SAP Debug configs.
 */
export function getUsedPorts(workspacePath: string): Set<number> {
  const config = readLaunchJson(workspacePath);
  const ports = new Set<number>();
  for (const c of config.configurations) {
    if (c.name.startsWith(LAUNCH_CONFIG_PREFIX) && typeof c.port === 'number') {
      ports.add(c.port);
    }
  }
  return ports;
}
