/**
 * Pure generator for the Verdaccio `config.yaml` that SAP Tools writes into
 * `~/.saptools/verdaccio/`. Kept dependency-free (hand-rolled YAML, no `yaml` package)
 * so it stays in line with the extension's "no extra runtime deps" stance and can be
 * unit-tested.
 *
 * The configured scopes (e.g. `@example`) are served purely locally (no uplink), so
 * publishing/installing them never touches npmjs; everything else proxies npmjs.
 */

export interface VerdaccioConfigOptions {
  readonly port: number;
  readonly scopes: readonly string[];
}

export function generateVerdaccioConfigYaml(options: VerdaccioConfigOptions): string {
  const scopeBlocks = options.scopes.map(
    (scope) =>
      `  '${scope}/*':\n` +
      `    access: $all\n` +
      `    publish: $all\n` +
      `    unpublish: $all`
  );

  const lines = [
    '# Generated by SAP Tools — local package registry.',
    '# Safe to delete; it is regenerated every time the registry starts.',
    'storage: ./storage',
    `listen: localhost:${String(options.port)}`,
    'max_body_size: 100mb',
    'uplinks:',
    '  npmjs:',
    '    url: https://registry.npmjs.org/',
    '    cache: false',
    'auth:',
    '  htpasswd:',
    '    file: ./htpasswd',
    '    max_users: -1',
    'packages:',
    ...scopeBlocks,
    "  '@*/*':",
    '    access: $all',
    '    publish: $all',
    '    unpublish: $all',
    '    proxy: npmjs',
    "  '**':",
    '    access: $all',
    '    publish: $all',
    '    unpublish: $all',
    '    proxy: npmjs',
    'log:',
    '  type: stdout',
    '  format: pretty',
    '  level: warn',
    '',
  ];

  return lines.join('\n');
}
